challenge/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('list_posts.urls')),
    url(r'^admin/', admin.site.urls),
]

list_posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'list_posts'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='post'),
    url(r'^vote/(?P<post_id>[0-9]+)/$', views.vote, name='vote'),
    url(r'^upvote/(?P<post_id>[0-9]+)/$', views.up_vote, name='up_vote'),
    url(r'^downvote/(?P<post_id>[0-9]+)/$', views.down_vote, name='down_vote'),
    url(r'^posts/', views.list_posts, name='list_posts'),
]

list_posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import numpy as np
from django.utils import timezone
from math import sqrt
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Post(models.Model):
    pub_date = models.DateTimeField('Date Published', default=timezone.now)
    post_text = models.CharField('Post content', max_length=500)
    up_votes = models.PositiveIntegerField('Up votes', default=0)
    down_votes = models.PositiveIntegerField('Down votes', default=0)
    score = models.FloatField('Post Score', default=0)

    def __str__(self):
        return self.post_text

    def compute_score(self):
        """
        The compute_score function will compute the Wilson-score Interval,
        which calculation depends on the number of up/down votes and the total
        number of votes.
        Where:
         - p_hat - is the fraction of up votes out of total votes
         - total_votes - is the total number of votes
         - z - is the normal distribution, which, in order to have 95%
               of confidence, has to be equal to 1.96
        """

        total_votes = self.up_votes + self.down_votes
        if self.up_votes == 0:
            return 0
        else:
            p_hat = np.float64(self.up_votes) / total_votes
            z = np.float64(1.96)

            lower_bound = (((p_hat + z * z / (2 * total_votes)) - z * sqrt(
                (p_hat * (1 - p_hat) + z * z /
                 (4 * total_votes)) / total_votes)) / (1 + z * z / total_votes))

            return lower_bound

list_posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from django.views import generic
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from list_posts.models import Post


class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'list_posts/post.html'

    def get_queryset(self):
        """
        Excludes any posts that aren't published yet.
        """
        return Post.objects.filter(pub_date__lte=timezone.now())


def index(request):
    latest_posts_list = Post.objects.filter(
        pub_date__lte=timezone.now()).order_by('-pub_date')
    context = {'latest_posts_list': latest_posts_list}
    return render(request, 'list_posts/index.html', context=context)


def vote(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    try:
        vote_type = request.POST['vote']
    except (KeyError, Post.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'list_posts/post.html', {
            'post': post,
            'error_message': "You didn't voted.",
        })
    else:
        if vote_type == 'upvote':
            post.up_votes += 1
        elif vote_type == 'downvote':
            post.down_votes += 1
        post.score = post.compute_score()
        post.save()
        return HttpResponseRedirect(reverse('list_posts:post', args=(post_id,)))


def list_posts(request):
    ordered_posts_list = Post.objects.order_by('-score')
    context = {'latest_posts_list': ordered_posts_list}
    return render(request, 'list_posts/index.html', context=context)


def up_vote(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.up_votes += 1
    post.score = post.compute_score()
    post.save()

    return render(request, 'list_posts/results.html', {'post': post})


def down_vote(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.down_votes += 1
    post.score = post.compute_score()
    post.save()

    return render(request, 'list_posts/results.html', {'post': post})

list_posts/templates/list_posts/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'list_posts/style.css' %}" />

{% if latest_posts_list %}
<ul style="list-style: none;">
  {% for post in latest_posts_list %}
  <li style="font-family: Arial, Helvetica, sans-serif;">
    <a href="{% url 'list_posts:post' post.id %}">{{post.post_text}}</a>, published on {{post.pub_date}}
  </li><br />
  {% endfor %}
</ul>
{% else %}
<p>No posts are available.</p>
{% endif %}

list_posts/templates/list_posts/post.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'list_posts/style.css' %}" />

<h2>Post with id {{post.id}}</h2>

<p>{{post.post_text}}</p>

<p><strong>Results:</strong> {{post.up_votes}} Up vote{{post.up_votes|pluralize}} --
  {{post.down_votes}} Down vote{{post.down_votes|pluralize}} with a score of {{post.score}}</p>

{% if error_message %} <p><strong>{{error_message}}</strong></p> {% endif %}

<form action="{% url 'list_posts:vote' post.id %}" method="post">
  {% csrf_token %}
  <input type="radio" name="vote" id="upvote" value="upvote" />
  <label for="upvote">Up Vote</label>
  <br />
  <br />
  <input type="radio" name="vote" id="downvote" value="downvote" />
  <label for="downvote">Down Vote</label>
  <br />
  <br />
  <button type="submit" name="submit_vote" value="vote_btn">Vote</button>
</form>
<a href="{% url 'list_posts:index' %}">Go home?</a>

list_posts/templates/list_posts/results.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'list_posts/style.css' %}" />

<h4>{{ post.post_text }}</h4>

<p><strong>Results:</strong> {{post.up_votes}} Up vote{{post.up_votes|pluralize}} --
      {{post.down_votes}} Down vote{{post.down_votes|pluralize}} with a score of {{post.score}}</p>

<a href="{% url 'list_posts:index' %}">Go home?</a>